apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: eks.clusters.cnp.example.org
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  compositeTypeRef:
    apiVersion: clusters.cnp.example.org/v1alpha1
    kind: EKS
  resources:
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: VPC
      spec:
        cidrBlock: 192.168.0.0/16
        enableDnsSupport: true
        enableDnsHostNames: true
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: InternetGateway
      spec:
        vpcIdSelector:
          matchControllerRef: true
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: Subnet
      metadata:
        labels:
          zone: us-west-2a
          access: public
      spec:
        mapPublicIPOnLaunch: true
        cidrBlock: 192.168.64.0/18
        vpcIdSelector:
          matchControllerRef: true
        availabilityZone: us-west-2a
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: Subnet
      metadata:
        labels:
          zone: us-west-2b
          access: public
      spec:
        mapPublicIPOnLaunch: true
        cidrBlock: 192.168.128.0/18
        vpcIdSelector:
          matchControllerRef: true
        availabilityZone: us-west-2b
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: Subnet
      metadata:
        labels:
          zone: us-west-2c
          access: public
      spec:
        mapPublicIPOnLaunch: true
        cidrBlock: 192.168.192.0/18
        vpcIdSelector:
          matchControllerRef: true
        availabilityZone: us-west-2c
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: Subnet
      metadata:
        labels:
          zone: us-west-2a
          access: private
      spec:
        cidrBlock: 172.16.10.0/24
        vpcIdSelector:
          matchControllerRef: true
        availabilityZone: us-west-2a
        tags:
        - value: shared
        providerRef:
          name: cnp-aws
    patches:
      - fromFieldPath: metadata.annotations[crossplane.io/external-name]
        toFieldPath: spec.tags[0].key
        transforms:
        - type: string
          string:
            fmt: "kubernetes.io/cluster/%s"
    connectionDetails:
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: Subnet
      metadata:
        labels:
          zone: us-west-2b
          access: private
      spec:
        cidrBlock: 172.16.20.0/24
        vpcIdSelector:
          matchControllerRef: true
        availabilityZone: us-west-2b
        tags:
        - value: shared
        providerRef:
          name: cnp-aws
    patches:
      - fromFieldPath: metadata.annotations[crossplane.io/external-name]
        toFieldPath: spec.tags[0].key
        transforms:
        - type: string
          string:
            fmt: "kubernetes.io/cluster/%s"
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: Subnet
      metadata:
        labels:
          zone: us-west-2c
          access: private
      spec:
        cidrBlock: 172.16.30.0/24
        vpcIdSelector:
          matchControllerRef: true
        availabilityZone: us-west-2c
        tags:
        - value: shared
        providerRef:
          name: cnp-aws
    patches:
      - fromFieldPath: metadata.annotations[crossplane.io/external-name]
        toFieldPath: spec.tags[0].key
        transforms:
        - type: string
          string:
            fmt: "kubernetes.io/cluster/%s"
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: RouteTable
      spec:
        vpcIdSelector:
          matchControllerRef: true
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            gatewayIdSelector:
              matchControllerRef: true
        associations:
          - subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2a
                access: public
          - subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2b
                access: public
          - subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2c
                access: public
          - subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2a
                access: private
          - subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2b
                access: private
          - subnetIdSelector:
              matchControllerRef: true
              matchLabels:
                zone: us-west-2c
                access: private
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: network.aws.crossplane.io/v1alpha3
      kind: SecurityGroup
      spec:
        vpcIdSelector:
          matchControllerRef: true
        groupName: cnp-cluster
        description: Allow access to PostgreSQL
        ingress:
          - fromPort: 5432
            toPort: 5432
            protocol: tcp
            cidrBlocks:
              - cidrIp: 0.0.0.0/0
                description: Everywhere
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRole
      metadata:
        labels:
          role: controlplane
      spec:
        forProvider:
          assumeRolePolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Principal": {
                          "Service": [
                              "eks.amazonaws.com"
                          ]
                      },
                      "Action": [
                          "sts:AssumeRole"
                      ]
                  }
              ]
            }
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRolePolicyAttachment
      spec:
        forProvider:
          policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
          roleNameSelector:
            matchControllerRef: true
            matchLabels:
              role: controlplane
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: eks.aws.crossplane.io/v1beta1
      kind: Cluster
      spec:
        forProvider:
          roleArnSelector:
            matchControllerRef: true
            matchLabels:
              role: controlplane
          resourcesVpcConfig:
            endpointPrivateAccess: true
            enpointPublicAccess: false
            subnetIdSelector:
              matchControllerRef: true
          version: "1.16"
        providerRef:
          name: cnp-aws
    patches:
    - fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-eks-controlplane"
    connectionDetails:
    - fromConnectionSecretKey: kubeconfig
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRole
      labels:
        role: nodegroup
      spec:
        forProvider:
          assumeRolePolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Principal": {
                          "Service": [
                              "ec2.amazonaws.com"
                          ]
                      },
                      "Action": [
                          "sts:AssumeRole"
                      ]
                  }
              ]
            }
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRolePolicyAttachment
      spec:
        forProvider:
          policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          roleNameSelector:
            matchControllerRef: true
            matchLabels:
              role: nodegroup
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRolePolicyAttachment
      spec:
        forProvider:
          policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          roleNameSelector:
            matchControllerRef: true
            matchLabels:
              role: nodegroup
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRolePolicyAttachment
      spec:
        forProvider:
          policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          roleNameSelector:
            matchControllerRef: true
            matchLabels:
              role: nodegroup
        providerRef:
          name: cnp-aws
  - base:
      apiVersion: eks.aws.crossplane.io/v1alpha1
      kind: NodeGroup
      spec:
        forProvider:
          clusterNameSelector:
            matchControllerRef: true
          nodeRoleArnSelector:
            matchControllerRef: true
            matchLabels:
              role: nodegroup
          subnetSelector:
            matchControllerRef: true
            matchLabels:
              access: private
          scalingConfig:
            minSize: 1
            maxSize: 100
            desiredSize: 1
          instanceTypes:
          - t3.medium
        providerRef:
          name: cnp-aws
    patches:
      - fromFieldPath: metadata.annotations[crossplane.io/external-name]
        toFieldPath: metadata.annotations[crossplane.io/external-name]
      - fromFieldPath: "spec.parameters.nodes.count"
        toFieldPath: "spec.forProvider.scalingConfig.desiredSize"
      - fromFieldPath: "spec.parameters.nodes.size"
        toFieldPath: "spec.forProvider.instanceTypes[0]"
        transforms:
        - type: map
          map:
            small: t3.small
            medium: t3.medium
            large: t3.large
  - base:
      apiVersion: eks.aws.crossplane.io/v1alpha1
      kind: NodeGroup
      spec:
        forProvider:
          clusterNameSelector:
            matchControllerRef: true
          nodeRoleArnSelector:
            matchControllerRef: true
            matchLabels:
              role: nodegroup
          subnetSelector:
            matchControllerRef: true
            matchLabels:
              access: private
          scalingConfig:
            minSize: 1
            maxSize: 100
            desiredSize: 1
          instanceTypes:
          - t3.medium
        providerRef:
          name: cnp-aws
    patches:
      - fromFieldPath: metadata.annotations[crossplane.io/external-name]
        toFieldPath: metadata.annotations[crossplane.io/external-name]
      - fromFieldPath: "spec.parameters.nodes.count"
        toFieldPath: "spec.forProvider.scalingConfig.desiredSize"
      - fromFieldPath: "spec.parameters.nodes.size"
        toFieldPath: "spec.forProvider.instanceTypes[0]"
        transforms:
        - type: map
          map:
            small: t3.small
            medium: t3.medium
            large: t3.large
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Provider
    patches:
    - fromFieldPath: spec.writeConnectionSecretToRef.namespace
      toFieldPath: spec.credentialsSecretRef.namespace
    - fromFieldPath: spec.writeConnectionSecretToRef.name
      toFieldPath: spec.credentialsSecretRef.name
