---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: clusters.cnp.example.org
spec:
  defaultCompositionRef:
    name: clusters.cnp.example.org
  # Composite resources are cluster scoped, but each composite resource may
  # optionally support a namespaced 'composite resource requirement'. A
  # requirement acts as a proxy for its composite resource - changes made to the
  # requirement are reflected on the composite resource. A requirement shares
  # the API group and schema of its corresponding composite resouce, but must
  # have a different name. Omit the requirement names when defining a composite
  # resource that should not support a corresponding requirement resource.
  requirementNames:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  # This policy determines whether Crossplane will automatically create cluster
  # roles for this composite resource and its requirement. ManageClusterRoles is
  # the default. Under this policy Crossplane will create edit and view RBAC
  # cluster roles for the composite resource and requirement (if any). The roles
  # will aggregate to the Crossplane service account, crossplane-admin role, the
  # global edit and view roles, and any matching namespaced edit and view roles.
  rbacPolicy: ManageClusterRoles
  connectionSecretKeys:
  - kubeconfig
  # Note that there is no distinct UI metadata; UI forms are derived from the
  # crdSpecTemplate, which includes enough detail to infer how to build a form.
  crdSpecTemplate:
    group: cnp.example.org
    version: v1alpha1
    names:
      kind: AllocatedCluster
      listKind: AllocatedClusterList
      plural: allocatedclusters
      singular: allocatedcluster
    validation:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: Cluster configuration parameters.
                nodes:
                  type: object
                  description: Cluster node configuration parameters.
                  count:
                    type: int
                    description: Desired node count, from 1 to 100.
                  size:
                    type: string
                    description: Size of node.
                    enum:
                    - small
                    - medium
                    - large
                  required:
                  - count
                  - size
                logging:
                  type: object
                  description: Splunk logging configuration for cluster logs.
                  token:
                    type: string
                    description: Splunk API token.
                  required:
                  - token
                required:
                - nodes
                - splunk
            required:
            - parameters
