apiVersion: apiextensions.crossplane.io/v1alpha1
kind: Composition
metadata:
  name: fluentbits.helm.cnp.example.org
  labels:
    provider: helm
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  reclaimPolicy: Delete
  compositeResource:
    apiVersion: charts.cnp.example.org/v1alpha1
    kind: FluentBit
  composedResources:
  - base:
      apiVersion: helm.crossplane.io/v1alpha1
      kind: Release
      spec:
        forProvider:
          chart:
            name: fluent-bit
            repository: https://kubernetes-charts.storage.googleapis.com
          namespace: kube-system
          set:
          - name: image.fluent_bit.tag
            value: "1.3.7"
          - name: backend.splunk.host
            value: "127.0.0.1"
          - name: backend.splunk.port
            value: "8088"
          - name: backend.splunk.token
    patches:
      - fromFieldPath: spec.providerRef.name
        toFieldPath: spec.providerRef.name
      - fromFieldPath: spec.parameters.version
        toFieldPath: spec.set[0].value
      - fromFieldPath: spec.parameters.splunk.host
        toFieldPath: spec.set[1].value
      - fromFieldPath: spec.parameters.splunk.port
        toFieldPath: spec.set[2].value
      - fromFieldPath: spec.parameters.splunk.token
        toFieldPath: spec.set[3].value